// Learn more about Tauri commands at https://tauri.app/develop/calling-rust/
mod browser;

use browser::{
    engine::{create_browser_window, close_browser_window, get_browser_window, get_all_windows, create_engine_tab, close_engine_tab, update_engine_tab_url, set_engine_active_tab, get_engine_window_tabs, get_engine_active_tab, create_webview_tab, show_webview_tab, hide_webview_tab, close_webview_tab, navigate_webview_tab},
    tabs::{create_tab, close_tab, update_tab_url, get_tab, get_all_tabs, set_active_tab, duplicate_tab, move_tab, pin_tab, unpin_tab, mute_tab, unmute_tab, reload_tab, stop_tab_loading, go_back, go_forward, zoom_in, zoom_out, reset_zoom},
    bookmarks::{add_bookmark, create_bookmark_folder, delete_bookmark, delete_bookmark_folder, update_bookmark, move_bookmark, search_bookmarks, get_bookmark_tree, get_folder_contents, export_bookmarks, import_bookmarks},
    history::{add_history_visit, remove_history_entry, clear_history, search_history, get_recent_history, get_most_visited, get_history_by_date, get_history_stats, get_history_suggestions, update_history_favicon, export_history, import_history},
    downloads::{start_download, cancel_download, pause_download, resume_download, remove_download, clear_completed_downloads, get_downloads, get_active_downloads, get_download_stats, set_download_directory, get_download_progress, export_downloads},
    settings::{get_settings, update_general_settings, update_appearance_settings, update_search_settings, update_download_settings, update_advanced_settings, add_search_engine, remove_search_engine, set_default_search_engine, reset_settings_to_defaults, export_settings, import_settings, get_search_url, get_suggestion_url},
    filters::{get_site_shields, update_filter_lists, get_global_stats, should_block_request},
    privacy::{update_privacy_settings_privacy, update_site_shields_privacy, load_privacy_settings, check_url},
    session::{create_session, save_current_session, restore_session, add_window_to_session, remove_window_from_session, update_window_in_session, add_tab_to_window, remove_tab_from_window, update_tab_in_window, update_tab_scroll_position, set_session_active_tab, get_saved_sessions, delete_session, clear_old_sessions, export_session, import_session, get_current_session, enable_auto_save},
    plugins::{install_plugin, uninstall_plugin, enable_plugin, disable_plugin, get_plugin, get_all_plugins, get_enabled_plugins, update_plugin_setting, get_plugin_setting, trigger_plugin_event, has_plugin_permission, get_plugins_by_hook, search_plugins, export_plugin_settings, import_plugin_settings, get_plugin_stats, validate_plugin_manifest},
};

#[tauri::command]
fn greet(name: &str) -> String {
    format!("Hello, {}! You've been greeted from Rust!", name)
}

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    tauri::Builder::default()
        .plugin(tauri_plugin_opener::init())
        .plugin(tauri_plugin_store::Builder::default().build())
        .plugin(tauri_plugin_fs::init())
        .plugin(tauri_plugin_http::init())
        .plugin(tauri_plugin_shell::init())
        .invoke_handler(tauri::generate_handler![
            greet,
            create_browser_window,
            close_browser_window,
            get_browser_window,
            get_all_windows,
            create_engine_tab,
            close_engine_tab,
            update_engine_tab_url,
            set_engine_active_tab,
            get_engine_window_tabs,
            get_engine_active_tab,
            create_webview_tab,
            show_webview_tab,
            hide_webview_tab,
            close_webview_tab,
            navigate_webview_tab,
            create_tab,
            close_tab,
            update_tab_url,
            get_tab,
            get_all_tabs,
            set_active_tab,
            duplicate_tab,
            move_tab,
            pin_tab,
            unpin_tab,
            mute_tab,
            unmute_tab,
            reload_tab,
            stop_tab_loading,
            go_back,
            go_forward,
            zoom_in,
            zoom_out,
            reset_zoom,
            add_bookmark,
            create_bookmark_folder,
            delete_bookmark,
            delete_bookmark_folder,
            update_bookmark,
            move_bookmark,
            search_bookmarks,
            get_bookmark_tree,
            get_folder_contents,
            export_bookmarks,
            import_bookmarks,
            add_history_visit,
            remove_history_entry,
            clear_history,
            search_history,
            get_recent_history,
            get_most_visited,
            get_history_by_date,
            get_history_stats,
            get_history_suggestions,
            update_history_favicon,
            export_history,
            import_history,
            start_download,
            cancel_download,
            pause_download,
            resume_download,
            remove_download,
            clear_completed_downloads,
            get_downloads,
            get_active_downloads,
            get_download_stats,
            set_download_directory,
            get_download_progress,
            export_downloads,
            get_settings,
            update_general_settings,
            update_appearance_settings,
            update_search_settings,
            update_download_settings,
            update_advanced_settings,
            add_search_engine,
            remove_search_engine,
            set_default_search_engine,
            reset_settings_to_defaults,
            export_settings,
            import_settings,
            get_search_url,
            get_suggestion_url,
            get_site_shields,
            update_filter_lists,
            get_global_stats,
            should_block_request,
            update_privacy_settings_privacy,
            update_site_shields_privacy,
            load_privacy_settings,
            check_url,
            create_session,
            save_current_session,
            restore_session,
            add_window_to_session,
            remove_window_from_session,
            update_window_in_session,
            add_tab_to_window,
            remove_tab_from_window,
            update_tab_in_window,
            update_tab_scroll_position,
            set_session_active_tab,
            get_saved_sessions,
            delete_session,
            clear_old_sessions,
            export_session,
            import_session,
            get_current_session,
            enable_auto_save,
            install_plugin,
            uninstall_plugin,
            enable_plugin,
            disable_plugin,
            get_plugin,
            get_all_plugins,
            get_enabled_plugins,
            update_plugin_setting,
            get_plugin_setting,
            trigger_plugin_event,
            has_plugin_permission,
            get_plugins_by_hook,
            search_plugins,
            export_plugin_settings,
            import_plugin_settings,
            get_plugin_stats,
            validate_plugin_manifest
        ])
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
